import csv, smtplib

port = 2525 
smtp_server = "smtp.mailtrap.io"
login = "f005d01b8db081" # paste your login generated by Mailtrap
password = "806d3e5797fc1b" # paste your password generated by Mailtrap

message = """Subject: Order confirmation
To: {recipient}
From: {sender}

Hello, 
My name is Geronimo Alonso and I am reaching out because we have certain 
asphalt engineering needs.
I will try to be as clear as possible. We own a commercial property in Doral in which we 
have started a renovation project in 2018. The project consisted among other things, 
in the retoration of the damaged parking lot, as well as percolation, etc.
We submited the plans with the city through an asphalt company, which has substantially increased
the price of the work after the approval from Miami Dade was issued.
We have received great references from you, and would like you to analyze the possibility of
submiting an offer to take over the project and finishing the work.

Geronimo Joaquin Alonso\n
Design At Doral \n
Ph: (786) 631 - 9446"""

Geronimo Alonso
geronimoalonso@icloud.com
sender = "geronimo.joaquin.alonso@gmail.com"

with smtplib.SMTP("smtp.mailtrap.io", 2525) as server:
    server.login(login, password)
    with open("contacts.csv") as file:
        reader = csv.reader(file)
        next(reader)  # it skips the header row
        for name, email in reader:
            server.sendmail(
               sender,
                email,
                message.format(name=name, recipient=email, sender=sender)
            )
            print(f'Sent to {name}')